# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: New Geographer
# Site name
name: Gulácsi András
# URL to site image. Site image is used when your site is shared via social media
# 1:1 aspect ratio with a minimum of 144x144 or maximum of 4096x4096 pixels
# Sizes are references from https://dev.twitter.com/cards/types/summary#reference
# image: https://location-of-image.com
email: guland@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Gulácsi András vagyok. Geoinformatikusként a legújabb web-alapú megoldásokat alkalmazom
  a földrajzi kutatásban, a földrajzi adatok feldolgozására és megjelenítésére a JavaScript
  nyelv erejével. Az alacsony színvonalú, elavult egyetemi tömegoktatás nem képes megfelelni
   a jelen kihívásainak és nem aknázza ki a legújabb IT-technológiákban rejlő nagy
   lehetőségeket. A tudásom 90%-át nem az egyetemen szereztem, programozni is magamtól
   tanultam meg. Az írásaimban és a készülő könyvemben az ideológiai alapú, utópisztikus
   gondolkodás ellen veszem fel a küzdelmet a tények, a tapasztalatok és a józan ész
   segítségével, hogy ne váljon a pusztító ideológiák martalékává a társadalom,
   szenvedést és nyomort hagyva maga után. A New Geographer – Új Geográfus blog
   egy újszerű szemléletben egyesíti a földrajzot az informatikával és a webfejlesztéssel.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.newgeographer.com" # the base hostname & protocol for your site, e.g. http://example.com

email: guland@protonmail.com
mobile: +36 20 442 7225
github_username: SalsaBoy990
twitter_username: "@UjGeografus"

# Google Analytics
# Remove # found before google_analytics to include Google Analytics to your
# Jekyll site. Then replace UA-########-# with your Google Analytics tracking ID
# google_analytics: UA-########-#

# set timezone
timezone: Europe/Budapest

show_related_posts: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
