# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title
title: New Geographer
# Site name
name: Gulácsi András
# URL to site image. Site image is used when your site is shared via social media
# 1:1 aspect ratio with a minimum of 144x144 or maximum of 4096x4096 pixels
# Sizes are references from https://dev.twitter.com/cards/types/summary#reference
# image: https://location-of-image.com

description: > # this means to ignore newlines until "baseurl:"
  Gulácsi András vagyok. Geoinformatikusként a legújabb web-alapú megoldásokat alkalmazom
  a földrajzi kutatásban, a földrajzi adatok feldolgozására és megjelenítésére a JavaScript
  nyelv erejével. Az alacsony színvonalú, elavult egyetemi tömegoktatás nem képes megfelelni
   a jelen kihívásainak és nem aknázza ki a legújabb IT-technológiákban rejlő nagy
   lehetőségeket. A tudásom 90%-át nem az egyetemen szereztem, programozni is magamtól
   tanultam meg. Az írásaimban és a készülő könyvemben az ideológiai alapú, utópisztikus
   gondolkodás ellen veszem fel a küzdelmet a tények, a tapasztalatok és a józan ész
   segítségével, hogy ne váljon a pusztító ideológiák martalékává a társadalom,
   szenvedést és nyomort hagyva maga után. A New Geographer – Új Geográfus blog
   egy újszerű szemléletben egyesíti a földrajzot az informatikával és a webfejlesztéssel.

short-description: Egy újszerű szemléletben egyesíti a földrajzot az informatikával és a webfejlesztéssel.
# the subpath of your site, e.g. /blog
baseurl: ""
# the base hostname & protocol for your site, e.g. http://example.com
url: "http://www.newgeographer.com"

# contact information
email: admin@newgeographer.com
mobile: +36 20 442 7225
github_username: SalsaBoy990
facebook: https://www.facebook.com/newgeographer
twitter_username: "@UjGeografus"

# google analytics
google_analytics: "UA-106020833-1"

# set timezone
timezone: Europe/Budapest

# show related posts
show_related_posts: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
